apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: match3-ingress
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: match3-service
                port:
                  number: 80